In [1]:
#!pip install biopython
#!pip install blosum

In [2]:
from Bio.Blast.Applications import NcbiblastpCommandline
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import uuid
from Bio.Seq import Seq
import blosum as bl
import re
import pandas as pd
import numpy as np

In [3]:
seqs = SeqIO.to_dict(SeqIO.parse("test/ab.fa", 'fasta'))
str(seqs['QBZ81690.1'].seq)

'MGQANTTIKGYSAVSQDALFATYGITEGDYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCASTGHALKSKVV'

In [4]:
#for line in open("VOGs/same_vog_seq_pairs.tsv"):

#data = line.rstrip().split()
data = ['', 'QBZ81690.1', '', 'AGO83968.2']

seq1 = SeqRecord(seqs[data[1]].seq,
                 id=seqs[data[1]].id)
seq2 = SeqRecord(seqs[data[3]].seq,
                 id=seqs[data[3]].id)
SeqIO.write(seq1, f"seq_1.fasta", "fasta")
SeqIO.write(seq2, f"seq_2.fasta", "fasta")

str(seq1.seq)

'MGQANTTIKGYSAVSQDALFATYGITEGDYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCASTGHALKSKVV'

In [5]:
output = NcbiblastpCommandline(query=f"seq_1.fasta", subject=f"seq_2.fasta", outfmt="6 qstart qseq sstart sseq")()[0]
if len(output) < 2:
    output = f"{seqs[data[1]].id}\t{seqs[data[3]].id}\t NO_HIT"
#output = output.split("\n")
print(output)

29	DYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCAS	41	EYAELKEKTIRIIVALPTQYLSADKGRAAIEAIRSGEPGREA-LYDEVWDAAMAYSRDIAA
16	QDALF	80	REALY

In [6]:
output2 = NcbiblastpCommandline(query=f"seq_1.fasta", subject=f"seq_2.fasta", outfmt="6 qstart sstart btop qend send")()[0]
print(output2)

29	41	DE1QAAEKLAKSEAKAT1ERRI1RV1ML1ETGQ1AL1PAEDDKRGAR3NE3TS1TECP1DRDETAE-1LYTDRE1RWAD1LADMRAWYQS2CI1SA	89	100
16	80	QRDE2FY	20	84

In [7]:
output3 = NcbiblastpCommandline(query=f"seq_1.fasta", subject=f"seq_2.fasta", outfmt=12)()[0]
print(output3)

{
  "Seq_annot": {
    "desc": [
      {
        "user": {
          "type": {
            "str": "Hist Seqalign"
          },
          "data": [
            {
              "label": {
                "str": "Hist Seqalign"
              },
              "data": {
                "bool": true
              }
            }
          ]
        }
      },
      {
        "user": {
          "type": {
            "str": "Blast Type"
          },
          "data": [
            {
              "label": {
                "str": "blastp"
              },
              "data": {
                "int": 2
              }
            }
          ]
        }
      },
      {
        "user": {
          "type": {
            "str": "Blast Database Title"
          },
          "data": [
            {
              "label": {
                "str": "n/a"
              },
              "data": {
                "bool": false
              }
            }
          ]
        }
      }
    ],
    "data": {
      "align": [
        {
          "type": "partial",
          "dim": 2,
          "score": [
            {
              "id": {
                "str": "score"
              },
              "value": {
                "int": 51
              }
            },
            {
              "id": {
                "str": "blast_score"
              },
              "value": {
                "int": 51
              }
            },
            {
              "id": {
                "str": "e_value"
              },
              "value": {
                "real": 9.9862252798672e-05
              }
            },
            {
              "id": {
                "str": "bit_score"
              },
              "value": {
                "real": 24.253410651829
              }
            },
            {
              "id": {
                "str": "num_ident"
              },
              "value": {
                "int": 21
              }
            },
            {
              "id": {
                "str": "comp_adjustment_method"
              },
              "value": {
                "int": 2
              }
            },
            {
              "id": {
                "str": "num_positives"
              },
              "value": {
                "int": 28
              }
            },
            {
              "id": {
                "str": "hsp_percent_coverage"
              },
              "value": {
                "real": 62.1161616161616
              }
            }
          ],
          "segs": {
            "denseg": {
              "dim": 2,
              "numseg": 3,
              "ids": [
                {
                  "local": {
                    "str": "Query_1"
                  }
                },
                {
                  "local": {
                    "str": "Subject_1"
                  }
                }
              ],
              "starts": [
                28,
                40,
                70,
                -1,
                71,
                82
              ],
              "lens": [
                42,
                1,
                18
              ],
              "strands": [
                "plus",
                "plus",
                "plus",
                "plus",
                "plus",
                "plus"
              ]
            }
          }
        },
        {
          "type": "partial",
          "dim": 2,
          "score": [
            {
              "id": {
                "str": "score"
              },
              "value": {
                "int": 15
              }
            },
            {
              "id": {
                "str": "blast_score"
              },
              "value": {
                "int": 15
              }
            },
            {
              "id": {
                "str": "e_value"
              },
              "value": {
                "real": 7.94231692807295
              }
            },
            {
              "id": {
                "str": "bit_score"
              },
              "value": {
                "real": 10.3862259188043
              }
            },
            {
              "id": {
                "str": "num_ident"
              },
              "value": {
                "int": 2
              }
            },
            {
              "id": {
                "str": "comp_adjustment_method"
              },
              "value": {
                "int": 2
              }
            },
            {
              "id": {
                "str": "num_positives"
              },
              "value": {
                "int": 5
              }
            },
            {
              "id": {
                "str": "hsp_percent_coverage"
              },
              "value": {
                "real": 5.55050505050505
              }
            }
          ],
          "segs": {
            "denseg": {
              "dim": 2,
              "numseg": 1,
              "ids": [
                {
                  "local": {
                    "str": "Query_1"
                  }
                },
                {
                  "local": {
                    "str": "Subject_1"
                  }
                }
              ],
              "starts": [
                15,
                79
              ],
              "lens": [
                5
              ],
              "strands": [
                "plus",
                "plus"
              ]
            }
          }
        }
      ]
    }
  }
}

In [8]:
#Identify the positive matches by looking directly in the score matrix? https://www.ncbi.nlm.nih.gov/Class/FieldGuide/BLOSUM62.txt
blosumDict = dict(bl.BLOSUM(62))

def Blosum(a, b):
    key = str(a.upper()) + str(b.upper())
    return blosumDict.get(key, np.nan)

Blosum("A", "N")

-2.0

In [9]:
def GetBlastIndices(start, blast):
    indices = [i for i in range(start, start + len(blast))]
    
    gaps = [i for i, c in enumerate(blast) if c == "-"]
    
    for gap in gaps:
        indices.insert(gap, -1)
        
    return indices[0:len(blast)]

GetBlastIndices(2, "abcd-efg")

[2, 3, 4, 5, -1, 6, 7, 8]

In [10]:
def BuildBlastDf(start1, blast1, start2, blast2):
    start1 = int(start1)
    start2 = int(start2)
    
    i1 = GetBlastIndices(start1, blast1)
    i2 = GetBlastIndices(start2, blast2)
    score = [Blosum(a,b) for (a,b) in list(zip(blast1, blast2))]
    
    df = pd.DataFrame({"BLOSUM62": score, "Query": list(blast1), "Subject": list(blast2), "QLoc": i1, "SLoc": i2})
    return df
    
testBlastDf = BuildBlastDf(2, "abcde", 1, "wxy-z")
testBlastDf

   BLOSUM62 Query Subject  QLoc  SLoc
0      -3.0     a       w     2     1
1      -1.0     b       x     3     2
2      -2.0     c       y     4     3
3       NaN     d       -     5    -1
4       4.0     e       z     6     4

In [13]:
def BlastAlign(seq1, seq2):
    blastRaw = NcbiblastpCommandline(query=seq1, subject=seq2, outfmt="6 qstart qseq sstart sseq")()[0]
    blastLines = blastRaw.splitlines()
    blastFields = [re.split(r'\t+', line) for line in blastLines]
    
    df = [BuildBlastDf(*blast) for blast in blastFields]
    
    return df
    
blastDFs = BlastAlign(f"seq_1.fasta", f"seq_2.fasta")
blastDFs

[    BLOSUM62 Query Subject  QLoc  SLoc
 0        2.0     D       E    29    41
 1        7.0     Y       Y    30    42
 2       -1.0     Q       A    31    43
 3       -1.0     A       E    32    44
 4       -2.0     K       L    33    45
 ..       ...   ...     ...   ...   ...
 56       5.0     R       R    85    96
 57       6.0     D       D    86    97
 58      -1.0     C       I    87    98
 59       4.0     A       A    88    99
 60       1.0     S       A    89   100

 [61 rows x 5 columns],
    BLOSUM62 Query Subject  QLoc  SLoc
 0       1.0     Q       R    16    80
 1       2.0     D       E    17    81
 2       4.0     A       A    18    82
 3       4.0     L       L    19    83
 4       3.0     F       Y    20    84]

In [14]:
def BuildBlastEMSAlignment(blastDf, emsPairs):
    blastDf["ESM align"] = blastDf[['QLoc', 'SLoc']].apply(tuple, axis=1).isin(emsPairs)
    return blastDf

testEmsAlign = [(2,2),(4,3),(7,7)]
BuildBlastEMSAlignment(testBlastDf, testEmsAlign)

   BLOSUM62 Query Subject  QLoc  SLoc  ESM align
0      -3.0     a       w     2     1      False
1      -1.0     b       x     3     2      False
2      -2.0     c       y     4     3       True
3       NaN     d       -     5    -1      False
4       4.0     e       z     6     4      False

In [15]:
# pasting in the calculated EMS pairs from other notebook for now
emsPairs = [(0, 0),  (9, 13),  (10, 14),  (12, 15),  (13, 22),  (14, 25),  (26, 28),  (29, 41),  (32, 47),  (37, 49),  (39, 50),  (40, 51),  
            (42, 54),  (44, 56),  (46, 58),  (47, 59),  (49, 61),  (52, 63),  (53, 65),  (54, 67),  (55, 67),  (56, 68),  (57, 69),  (58, 70),  
            (59, 71),  (60, 72),  (61, 73),  (62, 74),  (63, 75),  (64, 76),  (65, 77),  (66, 78),  (72, 82),  (75, 86),  (79, 87),  (80, 88),  
            (82, 93),  (83, 94),  (84, 95),  (85, 96),  (86, 97),  (87, 98),  (90, 100),  (92, 102),  (94, 104),  (96, 105)]

compareDf = BuildBlastEMSAlignment(blastDFs[0], emsPairs)
compareDf

    BLOSUM62 Query Subject  QLoc  SLoc  ESM align
0        2.0     D       E    29    41       True
1        7.0     Y       Y    30    42      False
2       -1.0     Q       A    31    43      False
3       -1.0     A       E    32    44      False
4       -2.0     K       L    33    45      False
..       ...   ...     ...   ...   ...        ...
56       5.0     R       R    85    96       True
57       6.0     D       D    86    97       True
58      -1.0     C       I    87    98       True
59       4.0     A       A    88    99      False
60       1.0     S       A    89   100      False

[61 rows x 6 columns]

In [28]:
def RenderAlignment(df):
    positive = pd.DataFrame(np.where(df.BLOSUM62 > 0.0, "+", None))
    perfect = pd.DataFrame(np.where(df.Query == df.Subject, "*", None))
    match = perfect.combine_first(positive).fillna(" ")
    
    print(str(compareDf.iloc[0].QLoc) + "\t" + "".join(df.Query) + "\t" + str(compareDf.iloc[-1].QLoc))
    print("\t" + "".join(match[0]))
    #print("\t" + "".join())
    print(str(compareDf.iloc[0].SLoc) + "\t" + "".join(df.Subject) + "\t" + str(compareDf.iloc[-1].SLoc))
    print("ESM:\t" + "".join(np.where(df["ESM align"], "@", " ")))
    
RenderAlignment(compareDf)

29	DYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCAS	89
	+*       *  * *+*  * * +   *** ***+*  * +  *   *  *   + ** *+
41	EYAELKEKTIRIIVALPTQYLSADKGRAAIEAIRSGEPGREA-LYDEVWDAAMAYSRDIAA	100
ESM:	@       @    @ @ @@ @   @ @@@@@@@@@@@@        @      @@@@@@