### Install dependencies

In [3]:
#!pip install NetworkX
#!pip install biopython
#!pip install blosum

### Imports

In [109]:
from Bio.Blast.Applications import NcbiblastpCommandline
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import uuid
from Bio.Seq import Seq
import blosum as bl
import re
import pandas as pd
import numpy as np
import tqdm
import torch
import pandas as pd
from Bio import SeqIO
import networkx as nx

C:\Users\levi\anaconda3\envs\BigDataMahdi\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Extract data

In [110]:
# import tarfile
  
# # open file
# file = tarfile.open('temp_outs.tar.gz')
  
# # extracting file
# file.extractall('./')
  
# file.close()

### Align sequences with ESM (code mostly from Mahdi)

In [111]:
seq_1 = torch.load(f"temp_outs\outputs\QBZ81690.1.pt")
seq_2 = torch.load(f"temp_outs\outputs\AGO83968.2.pt")
seq_1

{'label': 'QBZ81690.1',
 'representations': {36: tensor([[ 0.0305, -0.2712, -0.0361,  ..., -0.1840, -0.0522, -0.0922],
          [ 0.1543, -0.1236, -0.0234,  ..., -0.0630, -0.2551,  0.0359],
          [ 0.0661, -0.0476, -0.0673,  ..., -0.0502, -0.2257,  0.0975],
          ...,
          [ 0.0282,  0.0571,  0.0858,  ..., -0.0320, -0.1567,  0.0178],
          [ 0.0330, -0.1428,  0.0135,  ..., -0.0338, -0.0357, -0.1182],
          [-0.1102, -0.0696, -0.1198,  ..., -0.0898, -0.1002, -0.0122]])},
 'mean_representations': {36: tensor([ 0.0314, -0.0491, -0.0131,  ..., -0.0286, -0.0542,  0.0002])}}

In [112]:
# Compute all pairwise distances
data = []
for i in range(seq_1["representations"][36].shape[0]):
    line = []
    for j in range(seq_2["representations"][36].shape[0]):
        v1 = seq_1["representations"][36][i]
        v2 = seq_2["representations"][36][j]
        line.append(round(torch.cdist(v1.unsqueeze(0), v2.unsqueeze(0)).item(), 2))
    data.append(line)
    

# Write the matrix to the excel sheet    
data = pd.DataFrame(data)
data

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
0,4.85,7.74,7.44,7.62,7.52,7.21,7.61,7.44,7.18,7.28,...,6.24,6.36,6.65,6.82,6.46,6.24,6.15,6.01,6.34,6.48
1,7.78,7.29,7.96,8.19,7.94,7.76,8.02,8.16,6.97,7.92,...,7.32,7.48,6.56,7.47,7.37,7.08,6.90,6.80,7.03,7.06
2,7.28,7.33,7.06,7.43,6.92,6.78,7.45,7.38,7.08,6.97,...,6.10,6.50,6.66,6.32,6.13,6.07,5.90,5.94,6.17,6.29
3,7.18,7.67,7.11,7.23,7.23,6.96,7.19,7.27,7.15,7.04,...,5.16,5.61,6.76,6.65,4.90,4.80,5.86,5.65,6.08,6.43
4,6.94,7.04,6.88,7.00,6.83,6.72,7.06,6.98,6.90,6.79,...,5.89,6.30,6.44,6.50,5.93,5.53,5.38,5.39,5.81,6.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,6.73,7.26,6.89,7.00,6.54,5.83,6.99,6.91,6.42,6.58,...,5.15,5.68,5.81,5.82,5.24,4.84,3.61,4.52,5.04,5.47
95,7.01,7.47,7.12,7.47,6.89,6.76,7.27,7.35,6.78,6.77,...,5.82,6.21,6.13,6.37,5.70,5.29,5.10,4.82,5.43,5.90
96,6.74,7.25,6.88,7.10,6.58,5.84,6.94,6.98,6.63,6.58,...,5.30,5.81,5.82,5.88,5.28,4.91,3.84,4.44,4.80,5.37
97,7.12,7.52,7.38,7.54,7.10,6.96,7.25,7.33,6.98,7.20,...,5.98,6.23,6.38,6.48,5.85,5.49,5.29,4.96,5.08,5.76
98,7.21,7.60,7.45,7.50,7.18,7.12,7.46,7.37,7.17,7.23,...,6.13,6.41,6.69,6.74,6.15,5.91,5.80,5.67,5.63,5.05

In [113]:
seqs = SeqIO.to_dict(SeqIO.parse("test/ab.fa", 'fasta'))

seq_ids = list(seqs.keys())
seq_ids = [seq_ids[0]] + [seq_ids[1]]
seq_ids

['QBZ81690.1', 'AGO83968.2']

In [114]:
top_n = 5
rows = pd.DataFrame({n: data.T[col].nsmallest(top_n).index.tolist() 
                  for n, col in enumerate(data.T)}).T

cols = pd.DataFrame({n: data[row].nsmallest(top_n).index.tolist() 
                  for n, row in enumerate(data)})

matches = set()
for i, n_cols in enumerate(rows.values):
    for c in n_cols:
        if i in cols.iloc[:, c].values:
            matches.add((i, int(c)))

temp_set = set()
for match in matches:
    if match[0] > 0 and match[1] > 0 and (seqs[seq_ids[0]][match[0]-1] ==  seqs[seq_ids[1]][match[1]-1]):
            temp_set.add((match[0]-1, match[1]-1))
            #if sheet[(match[0]+1, match[1]+1)].color is None:
            #    sheet[(match[0]+1, match[1]+1)].color = "#82C341"
    if match[0] < len(seqs[seq_ids[0]]) - 1  and match[1] < len(seqs[seq_ids[1]])-1 and  (seqs[seq_ids[0]][match[0]+1] ==  seqs[seq_ids[1]][match[1]+1]):
            temp_set.add((match[0]+1, match[1]+1))
            #if sheet[(match[0]+1, match[1]+1)].color is None:
            #    sheet[( match[0]+3, match[1]+3)].color = "#82C341"

matches = matches.union(temp_set)
list(matches)[0:10]

[(38, 23),
 (16, 84),
 (78, 68),
 (96, 104),
 (36, 71),
 (27, 13),
 (18, 44),
 (79, 60),
 (29, 41),
 (74, 73)]

In [115]:
def build_paths_graph(matches):
    graph = nx.DiGraph()
    dag = {}
    max_depth = max([x[0] for x in matches])
    sorted_matches = sorted(matches, key=lambda x: x[1])
    for i in range(len(sorted_matches) - 1):
        last_depth =  max_depth
        dag[sorted_matches[i]] = []
        #print(f"Comparing {sorted_matches[i]} and {sorted_matches[j]}")
        for j in range(i+1, len(sorted_matches)):
            if (sorted_matches[j][0]) < last_depth and  (sorted_matches[j][0] >  sorted_matches[i][0]):
                dag[sorted_matches[i]].append(sorted_matches[j])
                seq_1_idx, seq_2_idx = sorted_matches[j]
                graph.add_edge(sorted_matches[i], sorted_matches[j], weigth=data.iloc[seq_1_idx, seq_2_idx])
                last_depth = sorted_matches[j][0]
    return graph


graph = build_paths_graph(matches)
esmAlignment = nx.dag_longest_path(graph)
#len(longest_path)
esmAlignment[0:10]

[(0, 0),
 (9, 13),
 (10, 14),
 (12, 15),
 (13, 22),
 (14, 25),
 (26, 28),
 (29, 41),
 (32, 47),
 (37, 49)]

### Align sequences with BLAST

In [116]:
seqs = SeqIO.to_dict(SeqIO.parse("test/ab.fa", 'fasta'))
str(seqs['QBZ81690.1'].seq)

'MGQANTTIKGYSAVSQDALFATYGITEGDYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCASTGHALKSKVV'

In [117]:
data = ['', 'QBZ81690.1', '', 'AGO83968.2']

seq1 = SeqRecord(seqs[data[1]].seq,
                 id=seqs[data[1]].id)
seq2 = SeqRecord(seqs[data[3]].seq,
                 id=seqs[data[3]].id)
SeqIO.write(seq1, f"seq_1.fasta", "fasta")
SeqIO.write(seq2, f"seq_2.fasta", "fasta")

str(seq1.seq)

'MGQANTTIKGYSAVSQDALFATYGITEGDYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCASTGHALKSKVV'

In [118]:
output = NcbiblastpCommandline(query=f"seq_1.fasta", subject=f"seq_2.fasta", outfmt="6 qstart qseq sstart sseq")()[0]
if len(output) < 2:
    output = f"{seqs[data[1]].id}\t{seqs[data[3]].id}\t NO_HIT"
#output = output.split("\n")
print(output)

29	DYQAKASAAIERIRAMPEGYASPEDRAAAINAIRTGTCGDDTELLTRVRAALDRWQRDCAS	41	EYAELKEKTIRIIVALPTQYLSADKGRAAIEAIRSGEPGREA-LYDEVWDAAMAYSRDIAA
16	QDALF	80	REALY

In [122]:
def GetBlastIndices(start, blast):
    indices = [i for i in range(start, start + len(blast))]
    
    gaps = [i for i, c in enumerate(blast) if c == "-"]
    
    for gap in gaps:
        indices.insert(gap, -1)
        
    return indices[0:len(blast)]

GetBlastIndices(2, "abcd-efg")

[2, 3, 4, 5, -1, 6, 7, 8]

In [124]:
def GetBlastAlignRegion(start1, blast1, start2, blast2):
    start1 = int(start1)
    start2 = int(start2)
    
    i1 = GetBlastIndices(start1, blast1)
    i2 = GetBlastIndices(start2, blast2)
    
    return list(zip(i1, i2))

testBlastIndices = GetBlastAlignRegion(2, "abcde", 1, "wxy-z")
testBlastIndices

[(2, 1), (3, 2), (4, 3), (5, -1), (6, 4)]

In [133]:
def BlastAlign(file1, file2):
    blastRaw = NcbiblastpCommandline(query=file1, subject=file2, outfmt="6 qstart qseq sstart sseq")()[0]
    blastLines = blastRaw.splitlines()
    blastFields = [re.split(r'\t+', line) for line in blastLines]
    
    alignments = [GetBlastAlignRegion(*blast) for blast in blastFields]
    
    return alignments
    
blastAlignments = BlastAlign(f"seq_1.fasta", f"seq_2.fasta")
[seq[0:10] for seq in blastAlignments]

[[(29, 41),
  (30, 42),
  (31, 43),
  (32, 44),
  (33, 45),
  (34, 46),
  (35, 47),
  (36, 48),
  (37, 49),
  (38, 50)],
 [(16, 80), (17, 81), (18, 82), (19, 83), (20, 84)]]

### Combine the results

In [69]:
def InterweaveAlignments(align1, align2):
    (indices11, indices12) = zip(*align1)
    (indices21, indices22) = zip(*align2)
    
    df1 = pd.DataFrame(data={"QLoc": indices11, "SLoc": indices12})
    #df1.set_index(keys=["QLoc", "SLoc"], inplace=True)
    
    df2 = pd.DataFrame(data={"QLoc": indices21, "SLoc": indices22})
    #df2.set_index(keys=["QLoc", "SLoc"], inplace=True)
    
    df = pd.merge(df1, df2, on=["QLoc", "SLoc"], how="outer", indicator=True, sort=True)
    #df.set_index(keys=["QLoc", "SLoc"], inplace=True)
    
    #split the indicator into bool columns
    df = pd.get_dummies(df, columns=["_merge"], prefix="")
    df["Align1"] = (df["_left_only"] | df["_both"]).astype(bool)
    df["Align2"] = (df["_right_only"] | df["_both"]).astype(bool)
    df = df.drop(columns=["_left_only","_right_only","_both"])
    
    return df
    
testAlign1 = [(1,1), (1,2), (2,2), (2,3), (3,3), (3,4), (4,4), (5,5)]
testAlign2 = [(0,0), (1,1), (1,2), (1,3), (1,4), (2,4), (3,4), (4,4)]
testAligns = InterweaveAlignments(testAlign1, testAlign2)
testAligns

    QLoc  SLoc  Align1  Align2
0      0     0   False    True
1      1     1    True    True
2      1     2    True    True
3      1     3   False    True
4      1     4   False    True
5      2     2    True   False
6      2     3    True   False
7      2     4   False    True
8      3     3    True   False
9      3     4    True    True
10     4     4    True    True
11     5     5    True   False

In [8]:
#Identify the positive matches by looking directly in the score matrix? https://www.ncbi.nlm.nih.gov/Class/FieldGuide/BLOSUM62.txt
blosumDict = dict(bl.BLOSUM(62))

def Blosum(a, b):
    key = str(a.upper()) + str(b.upper())
    return blosumDict.get(key, np.nan)

Blosum("A", "N")

-2.0

In [134]:
def CompareAlignments(query, subject, align1, align2):
    df = InterweaveAlignments(align1, align2)
    df["Query"] = [query[i] for i in df.QLoc]
    df["Subject"] = [subject[i] for i in df.SLoc]
    df["Score"] = [Blosum(a,b) for (a,b) in list(zip(df.Query, df.Subject))]
    
    return df

testSeq1 = ["a", "b", "c", "l", "e", "f"]
testSeq2 = ["t", "v", "c", "x", "m", "z"]
testAligns = CompareAlignments(testSeq1, testSeq2, testAlign1, testAlign2)
testAligns

    QLoc  SLoc  Align1  Align2 Query Subject  Score
0      0     0   False    True     a       t    0.0
1      1     1    True    True     b       v   -3.0
2      1     2    True    True     b       c   -3.0
3      1     3   False    True     b       x   -1.0
4      1     4   False    True     b       m   -3.0
5      2     2    True   False     c       c    9.0
6      2     3    True   False     c       x   -1.0
7      2     4   False    True     c       m   -1.0
8      3     3    True   False     l       x   -1.0
9      3     4    True    True     l       m    2.0
10     4     4    True    True     e       m   -2.0
11     5     5    True   False     f       z   -3.0

In [138]:
alignmentDFs = [CompareAlignments(seq1.seq, seq2.seq, blastAlign, esmAlignment) for blastAlign in blastAlignments]
alignmentDFs[0]

    QLoc  SLoc  Align1  Align2 Query Subject  Score
0      0     0   False    True     M       M    5.0
1      9    13   False    True     G       G    6.0
2     10    14   False    True     Y       Y    7.0
3     12    15   False    True     A       A    4.0
4     13    22   False    True     V       V    4.0
..   ...   ...     ...     ...   ...     ...    ...
75    89   100    True   False     T       G   -2.0
76    90   100   False    True     G       G    6.0
77    92   102   False    True     A       A    4.0
78    94   104   False    True     K       K    5.0
79    96   105   False    True     K       P   -1.0

[80 rows x 7 columns]

### Render the comparison

In [106]:
def SeqString(conditions, values, blank=" "):
    chars = np.select([conditions, ~conditions], [values, blank])
    return "".join(chars)

SeqString(pd.Series([False, True, True, False]), [1, 2, 3, 4])

' 23 '

In [108]:
def RenderAlignments(df):
    positive = pd.DataFrame(np.where(df.Score > 0.0, "+", None))
    perfect = pd.DataFrame(np.where(df.Query == df.Subject, "*", None))
    score = perfect.combine_first(positive)[0].fillna(" ")
    
    a1_condition = [df.Align1, ~df.Align1]
    a2_condition = [df.Align2, ~df.Align2]
    
    #alignment 1
    print(SeqString(df.Align1, df.Query))
    print(SeqString(df.Align1, score))
    print(SeqString(df.Align1, df.Subject))
    
    #anchors
    print(SeqString(df.Align1&df.Align2, "|"))
    
    #alignment 2
    print(SeqString(df.Align2, df.Query))
    print(SeqString(df.Align2, score))
    print(SeqString(df.Align2, df.Subject))
    
RenderAlignments(testAligns)

 bb  cc llef
     *   +
 vc  cx xmmz
 ||      ||
abbbb  c le
         +
tvcxm  m mm

In [139]:
RenderAlignments(alignmentDFs[0])

       YQAK ASAAIE R IRAMPEGYASPE DRA AAINAIRTGTCGDDTEL LTRVRAA L DRWQRDCAST
       *        *    * *+*  * * +     *** ***+*  * +       *  *     + ** *+
       YAEL KEKTIR I IVALPTQYLSAD KGR AAIEAIRSGEPGREALR YDEVWDA A MAYSRDIAAG
       |        |      | | || |    |  ||||||||||||         |        ||||||
MGYAVSEY   K    I R I  A P GY S  D R AAAINAIRTGTCG     L   V   L D  WQRDCA  GAKK
********   *    * * *  * *  * *  *   **** ***+*  *     *   *     *  + ** *  ***
MGYAVSEY   K    I R I  A P QY S  D G AAAIEAIRSGEPG     L   V   W D  YSRDIA  GAKP

In [141]:
RenderAlignments(alignmentDFs[1])

      DALFA
      +**+
      EALYD

MGYAVS     EYKIRIAPGYSDRAAAINAIRTGTCGLVLDWQRDCAGAKK
******     ******** *** **** ***+*  *** *+ ** ****
MGYAVS     EYKIRIAPQYSDGAAAIEAIRSGEPGLVWDYSRDIAGAKP

### ToDo: confirm whether this is rendering InDels in the BLAST alignment correctly